### ISSUE TITLE
com.google.apphosting.utils.config.AppEngineConfigException: Could not locate /tmp/tmpEarArea5562840872139100552/WEB-INF/appengine-web.xml

### ISSUE THREAD

**Issue by ibrahimali123** [GoogleCloudPlatform/appengine-plugins#1027]
I am using Java 21 and also using cloudSdkVersion 449 in my pom.xml to be able to run the project locally but I can't comment the version line. I want to use the latest version but it shows the below error when running the project:

![Screenshot from 2024-07-13 15-39-31](https://github.com/user-attachments/assets/f58c74d7-ae0a-4bd7-97b0-838a2a867d8d)

I have received this error recently after the update of version 450:

INFO] GCLOUD: Jul 13, 2024 3:20:28 PM com.google.apphosting.utils.config.AppEngineWebXmlReader readAppEngineWebXml
[INFO] GCLOUD: SEVERE: Received exception processing /tmp/tmpEarArea5562840872139100552/WEB-INF/appengine-web.xml
[INFO] GCLOUD: com.google.apphosting.utils.config.AppEngineConfigException: Could not locate /tmp/tmpEarArea5562840872139100552/WEB-INF/appengine-web.xml
[INFO] GCLOUD: 	at com.google.apphosting.utils.config.AppEngineWebXmlReader.getInputStream(AppEngineWebXmlReader.java:155)
[INFO] GCLOUD: 	at com.google.apphosting.utils.config.AppEngineWebXmlReader.readAppEngineWebXml(AppEngineWebXmlReader.java:89)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.SharedMain.configureRuntime(SharedMain.java:225)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:356)
[INFO] GCLOUD: 	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:58)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:239)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:230)
[INFO] GCLOUD: Caused by: java.io.FileNotFoundException: /tmp/tmpEarArea5562840872139100552/WEB-INF/appengine-web.xml (No such file or directory)
[INFO] GCLOUD: 	at java.base/java.io.FileInputStream.open0(Native Method)
[INFO] GCLOUD: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
[INFO] GCLOUD: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
[INFO] GCLOUD: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
[INFO] GCLOUD: 	at com.google.apphosting.utils.config.AppEngineWebXmlReader.getInputStream(AppEngineWebXmlReader.java:151)
[INFO] GCLOUD: 	... 6 more
[INFO] GCLOUD:

**Comment by mayorchyk** [comment]
I'm facing the same issue when trying to launch Java 17 based multi-module application on local dev environment with `appengine:run`.
appengine-maven-plugin version: 2.8.1

Plugin configuration:
```
<plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <configuration>
          <deploy.projectId>${app.deploy.projectId}</deploy.projectId>
          <deploy.version>${app.deploy.version}</deploy.version>
          <cloudSdkVersion>${googlecloud.sdk.version}</cloudSdkVersion>
          <services>
            <!-- default service -->
            <service>${project.build.directory}/${project.name}-${project.version}</service>
            <!-- One for each additional service -->
            <service>
              ${project.parent.basedir}/other_module/target/other_module_finalName-${project.version}
            </service>
          </services>
          <promote>false</promote>
          <enableJarClasses>true</enableJarClasses>
          <enableJarSplitting>true</enableJarSplitting>
          <deleteJsps>false</deleteJsps>
          <port>8888</port>
          <jvmFlags>
           <!-- omitted -->
          </jvmFlags>
        </configuration>
      </plugin>
```

**Comment by ibrahimali123** [comment]
@mayorchyk I can't run it until now; I can only run using Cloud SDK version 449. I'm not sure if they will provide a fix, but please let me know if you find any help for this. Thanks :)

**Comment by Tiboafx** [comment]
This issue is also reported here : https://issuetracker.google.com/issues/360704493

**Comment by mayorchyk** [comment]
@ibrahimali123 the fix has been released: https://groups.google.com/g/google-cloud-sdk-announce/c/yndjJVhnUCw

**Comment by mpeddada1** [comment]
Hey @ibrahimali123, to double check, does setting `cloudSdkVersion` to `494` address your issue?

**Comment by mpeddada1** [comment]
Closing due to lack of response.
